language: node_js
node_js:
  - "10"
  - "11"
  - "12"
cache: npm
install:
  - npm i
script:
  - npm run build
deploy:
  - provider: npm
    skip_cleanup: true
    email: imazzine.development.kit@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    local_dir: ./design/svg
    keep_history: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master