language: node_js
node_js:
  - "14"
services:
  - docker
before_install:
  - docker pull node:14-alpine3.10
install:
  - mkdir coverage
  - npm i
  - docker build -t zz:cli-test .
script:
  - docker run -v "$(pwd)"/coverage:/cli/coverage -t zz:cli-test
  - ./node_modules/.bin/coveralls < ./coverage/lcov.info
before_deploy:
  - npm version $TRAVIS_TAG --no-git-tag-version
  - git config user.email "$GIT_EMAIL"
  - git config user.name "$GIT_NAME"
  - git checkout $TRAVIS_BRANCH
  - git add ./package.json ./package-lock.json
  - git commit -m "Bump version to $TRAVIS_TAG"
  - git push origin $TRAVIS_BRANCH 2>&1
  - git push origin $TRAVIS_BRANCH --tags 2>&1
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true