language: node_js
node_js:
  - "14"
services:
  - docker
before_install:
  - docker pull node:14-alpine3.10
install:
  - mkdir coverage
  - npm i
  - docker build -t zz:cli-test .
script:
  - docker run -v "$(pwd)"/coverage:/cli/coverage -t zz:cli-test
  - ./node_modules/.bin/coveralls < ./coverage/lcov.info

# language: node_js
# node_js:
#   - "14"
# cache: npm
# install:
#   - npm i -g @imazzine/cli
#   - npm i -g @imazzine/tmp
#   - npm i
# script:
#   - npm run test:ci
# deploy:
#   - provider: npm
#     skip_cleanup: true
#     email: imazzine.development.kit@gmail.com
#     api_key: $NPM_TOKEN
#    on:
#      tags: true
#   - provider: pages
#     skip_cleanup: true
#     keep_history: true
#     github_token: $GITHUB_TOKEN
#     on:
#       branch: master