language: node_js
node_js:
  - "14"
services:
  - docker
before_install:
  - docker pull node:14-alpine3.10
install:
  - mkdir coverage
  - npm i
  - docker build -t zz:cli-test .
script:
  - docker run -v "$(pwd)"/coverage:/cli/coverage -t zz:cli-test
  - ./node_modules/.bin/coveralls < ./coverage/lcov.info
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    all_branches: false