language: node_js
node_js:
  - "14"
services:
  - docker
before_install:
  - docker pull node:14-alpine3.10
install:
  - mkdir coverage
  - npm i
  - docker build -t zz:cli-test .
script:
  - docker run -v "$(pwd)"/coverage:/cli/coverage -t zz:cli-test
  - ./node_modules/.bin/coveralls < ./coverage/lcov.info