@startuml index
title Table of content
object "./deployment" as deployment {
    +[[./../deployment/nodes_graph.svg Nodes Graph]]
    +[[./../deployment/services_graph.svg Services Graph]]
}
object "./cli" as cli {
    +[[./../cli/deployment_graph.svg Deployment Graph]]
}
@enduml